;; -*- mode: emacs-lisp -*-
;; fsc.el: Autogenerated on Thu Sep 16 15:01:14 2010
(scala-fsc :classes "bin" :classpath
           '("lib/*.jar" "/usr/local/appengine-java-sdk/lib/*.jar"
             "/usr/local/appengine-java-sdk/lib/agent/*.jar"
             "/usr/local/appengine-java-sdk/lib/impl/*.jar"
             "/usr/local/appengine-java-sdk/lib/impl/agent/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/jsp/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/testing/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/tools/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/tools/jsp/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/tools/orm/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/tools/user/*.jar"
             "/usr/local/appengine-java-sdk/lib/shared/tools/user/orm/*.jar")
           :source "src" :clean-compile "ant clean all" :compile "ant")
